openapi/components/schemas/Challenge.yaml
openapi/components/schemas/Grant.yaml
openapi/components/schemas/Organization.yaml

As discussed:
- `organizations: List[Organization]` has been added to `Challenge`
- removed `Grant.amount`
- updated the required values for Grant to `name` and `url`
I also added `shortName` to `Organization` for fun-sies (:

Update schemas for Challenge, Grant, and Organization

---

openapi/components/schemas/TagFilter.yaml
openapi/paths/tags.yaml

Implements #31 
API service implementation: https://github.com/Sage-Bionetworks/rocc/pull/34

Add TagFilter schema and use it to filter list of tags

---

openapi/components/responses/InternalServerError.yaml
openapi/paths/challenges.yaml
openapi/paths/challenges@{challengeId}.yaml
openapi/paths/grants.yaml
openapi/paths/grants@{grantId}.yaml
openapi/paths/organizations.yaml
openapi/paths/organizations@{organizationId}.yaml
openapi/paths/persons.yaml
openapi/paths/persons@{personId}.yaml
openapi/paths/tags.yaml
openapi/paths/tags@{tagId}.yaml

With this PR:
- schema added for InternalServerError
- 500 error added to each endpoint
This will address #55 and can be implemented for v0.1.4 (#56)

Add `500 Internal Server Error` to endpoints

---

README.md
openapi/openapi.yaml
package-lock.json
package.json

- Bump spec version to 0.1.4 (#56)
- Bump project to version 0.1.4

bump spec and project to 0.1.4

---

openapi/paths/challenges.yaml
openapi/paths/grants.yaml
openapi/paths/organizations.yaml
openapi/paths/persons.yaml
openapi/paths/tags.yaml
openapi/paths/users.yaml

With this PR:
* add new DELETE path so that all entities of one schema type will be removed (#67)

add DELETE operation to remove all entities of one schema type

---

.gitignore
package-lock.json
package.json

Version 0.3.6 of the npm package `gh-openapi-docs-ts` solves the issue that was affecting version 0.3.5.
See https://github.com/Sage-Bionetworks/gh-openapi-docs/issues/6

Update gh-openapi-docs-ts to 0.3.6

---

.github/workflows/ci.yml
package-lock.json
package.json

Update dependencies and add other improvements.

Update package.json and CI workflow

---

openapi/components/schemas/ChallengeCreateRequest.yaml

refer to https://github.com/Sage-Bionetworks/rocc/issues/89
Two changes for the createChallenge request in this PR:
- make dates optional 
- add dataProviders that require OrganizationIds
Ps data for grants property is not ready yet.

Make dates optional and add dataProviders

---

.validaterc
package-lock.json
package.json

Update IBM validator config

---

openapi/components/schemas/ChallengeCreateRequest.yaml

Adding challenge's summary that will be used for the preview card for now.

Add summary of challenge

---

openapi/components/parameters/ChallengeId.yaml
openapi/components/schemas/GrantCreateResponse.yaml
openapi/paths/challenges.yaml
openapi/paths/grants.yaml
openapi/paths/organizations.yaml
openapi/paths/persons.yaml
openapi/paths/tags.yaml

- Remove 400 error from "delete all" endpoints
- Update `ChallengeId`

Prepare schemas for version 0.1.6

---

openapi/components/schemas/PageOfChallenges.yaml
openapi/components/schemas/PageOfGrants.yaml
openapi/components/schemas/PageOfOrganizations.yaml
openapi/components/schemas/PageOfPersons.yaml
openapi/components/schemas/PageOfTags.yaml
openapi/components/schemas/PageOfUsers.yaml

Update required properties of page schemas

---

openapi/components/parameters/ChallengePlatformId.yaml

Add more challenge platforms
@rrchai Are there other challenge platforms that you would like to see included in the list?

Add challenge platform listed in landscape

---

openapi/components/links/DeleteChallengePlatformById.yaml
openapi/components/links/GetChallengePlatformById.yaml
openapi/components/parameters/ChallengePlatformId.yaml
openapi/components/schemas/ChallengeCreateRequest.yaml
openapi/components/schemas/ChallengePlatform.yaml
openapi/components/schemas/ChallengePlatformCreateRequest.yaml
openapi/components/schemas/ChallengePlatformCreateResponse.yaml
openapi/components/schemas/PageOfChallengePlatforms.yaml
openapi/openapi.yaml
openapi/paths/challengePlatforms.yaml
openapi/paths/challengePlatforms@{challengePlatformId}.yaml

Fixes #131 
See [documentation preview](https://sage-bionetworks.github.io/rocc-schemas/pr-132/docs/)

Add platform endpoints

---

openapi/paths/challenges.yaml
openapi/paths/parameters/challenge/startDateRange.yaml

Filter challenges by start date

---

openapi/components/parameters/ChallengeStatus.yaml
openapi/components/schemas/ChallengeCreateRequest.yaml

Update challenge status with more descriptive values

---

openapi/components/schemas/DateRange.yaml
openapi/paths/parameters/challenge/startDateRange.yaml

Attempt to fix [this issue](https://github.com/Sage-Bionetworks/rocc-service/pull/132#issuecomment-881924072) that affect the API service.

Fix start date range

---

openapi/components/schemas/DateRange.yaml

- Rename `DateRange.startDate` to `DateRange.start`
- Rename `DateRange.endDate` to `DateRange.end`

Use now DateRange.start and DateRange.end

---

openapi/components/schemas/User.yaml
openapi/components/schemas/UserCreateRequest.yaml

Move properties name and avatarUrl to UserCreateRequest

---

openapi/components/schemas/ChallengeCreateRequest.yaml

Add Challenge.doi

---

README.md
openapi/openapi.yaml

Bump project version to 0.4.0

---

openapi/components/schemas/Challenge.yaml
openapi/components/schemas/ChallengeCreateRequest.yaml

Add Challenge.ownerId

---

openapi/components/schemas/Challenge.yaml
openapi/components/schemas/ChallengeCreateRequest.yaml
openapi/paths/challenges@{accountName}.yaml

Add GET /challenges/{accountName}

---

openapi/openapi.yaml
openapi/paths/user/orgs.yaml
openapi/paths/user/starred@{accountName}@{challengeName}.yaml
openapi/paths/users@{userId}orgs.yaml
openapi/paths/users@{userId}starred.yaml

Get user orgs

---

openapi/components/schemas/Organization.yaml
openapi/components/schemas/OrganizationCreateRequest.yaml

Move properties from Organization to OrganizationCreateRequest

---

openapi/components/schemas/User.yaml
openapi/components/schemas/UserCreateRequest.yaml

Add User.bio

---

openapi/components/parameters/ChallengeReadmeId.yaml
openapi/components/schemas/ChallengeReadme.yaml
openapi/components/schemas/ChallengeReadmeCreateRequest.yaml
openapi/components/schemas/ChallengeReadmeCreateResponse.yaml
openapi/components/schemas/ChallengeReadmeUpdateRequest.yaml
openapi/openapi.yaml
openapi/paths/challenges@{accountName}@{challengeName}readme.yaml

Add components for challenge readme

---

openapi/paths/challenges@{accountName}.yaml

Add searchTerm for querying the challenges from an account, in order to implement 
- https://github.com/Sage-Bionetworks/rocc-app/issues/308
(not sure if this file is only file needed to modify)

Add searchTerm on listAccountChallenges

---

openapi/components/parameters/TagId.yaml
openapi/components/parameters/TagName.yaml
openapi/openapi.yaml
openapi/paths/parameters/tagIds.yaml

Remove the remaining references to "tags", which have been replaced by "topics".

Remove tags

---

openapi/components/parameters/ChallengeIncentiveType.yaml
openapi/components/schemas/ChallengeCreateRequest.yaml
openapi/paths/challenges.yaml
openapi/paths/parameters/challenge/incentiveTypes.yaml

- #205 
Incentive Types
- Monetary
- Publication
- Speaking Engagement
- Other

add incentive type property and filter

---

openapi/components/parameters/ChallengeSubmissionType.yaml
openapi/components/schemas/ChallengeCreateRequest.yaml
openapi/paths/challenges.yaml
openapi/paths/parameters/challenge/submissionTypes.yaml

- https://github.com/Sage-Bionetworks/rocc-schemas/issues/205
Submission Types:
- DockerImage
- PredictionFile
- Other

Add submission type property and filter

---

openapi/components/parameters/ChallengeDifficulty.yaml
openapi/components/schemas/ChallengeCreateRequest.yaml
openapi/paths/challenges.yaml
openapi/paths/parameters/challenge/difficulty.yaml

- #205 
Difficulty Levels:
- GoodForBeginners
- Intermediate
- Advanced

add difficulty level property and filter
